from .attendance import Attendance
from .class_room import ClassRoom
from .fee import Fee
from .mark import Mark
from .student import Student
from .subject import Subject
from .teacher import Teacher
from .timetable import Timetable
from .user import User
